version: '3.2'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    # volumes:
    #   - ./data:/data/db


